### ISSUE TITLE
Generic "Close" button

### ISSUE THREAD

**Issue by jaghaimo** [Lukas22041/LunaLib#1]
Call it a brain fart or whatever, but it took me good 20 seconds to hit Esc when I didn't want to make any change / just close LunaLib. Please add `Close [Esc]` button below `Search Mod`, or maybe even at the top. Perhaps:

- `Save all and close [Enter]`
- `Close without saving [Esc]`
- `Save all`
- other current buttons

![image](https://github.com/Lukas22041/LunaLib/assets/1764586/988792f8-c9fe-45ef-8caf-6864bc1bb44c)

**Comment by jaghaimo** [comment]
Similar for Version Checker - a `Close` button at the top would be great. Sometimes your hand is just on a mouse and you don't want to look for the keyboard ;)

**Comment by Lukas22041** [comment]
This is already planned for when il get to it. However instead of being integrated in to the panel, the close button would be in the top right corner of the screen, to keep consistency with Vanillas implementation of Panels. Seperating the current save button in to 3 different ones would also take up to much space in certain UI-Scalings.
